### ISSUE TITLE
게임 재시작 할 때 game_results DB가 생성이 안됩니다

### ISSUE THREAD

**Issue by wkddlstn1321** [PingPong-IO/backend#14]
@lilllee 
Game이 끝났을 때 MatchingResult 를 보낼 수 있습니다.
MatchingResult를 매개변수로 보내면 
GameResultsService 에서 새로운 컬럼 추가하고 result_id 리턴해주는 매서드를 정의해 줄 수 있나요?

**Comment by lilllee** [comment]
@wkddlstn1321 그 확인하고 싶은부분이
1. 게임이 끝났을때라면 
   - GameResultsService 클래스 finishGame 메서드가 맞는지
2. GameResultsService 에서 새로운 컬럼 추가하고 result_id 리턴해주는 매서드를 만들어야한다.
   - 해당 부분에서는 result_id 만 return 만 시키면 되는지

**Comment by wkddlstn1321** [comment]
@lilllee 

https://github.com/PingPong-IO/backend/blob/67b5e39b039822f0c2e87df3a760c86745cebdc3/src/main/java/com/example/pingpong/game/dto/GameInformations/OneOnOneNormalGameInformation.java#L140-L160

1. GameInformation 클래스 restart 함수에서 필요합니다.
   * finishGame은 결과를 저장하는 역할입니다.
2. 맞습니다.
   * 156번째 줄에서 사용할 수 있게 result_id 만 리턴해주면 됩니다.
   * 새로운 컬럼을 추가할 때는 실제로 게임이 시작될 때 만드는 것과 똑같은 형태로 추가해 주시면 됩니다.
